### PR TITLE
improve ssh file configurations logic

### PR DESCRIPTION
**Pull request by jotheeswaran-dev**
refactor: improve  logic for incorporating `~/.ssh/global_config`

### CODE REVIEW

**Review by vraravam — CHANGES_REQUESTED** [review]
nice! we need to include this into the CHANGELOG.md before the PR can be merged

**Comment by jotheeswaran-dev** [comment]
comments incorporated 

> nice! we need to include this into the CHANGELOG.md before the PR can be merged

**Review by vraravam — APPROVED** [review]

**Review by vraravam — CHANGES_REQUESTED** [review]
@jotheeswaran-dev - please add your name to the list of contributors in the README file in this PR

**Review by vraravam — APPROVED** [review]
LGTM!

**Pull request merged**
